name: Build & Test BlobOS

on:
  push:
    branches: [ development ]
  pull_request:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  ubuntu:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Rust Nightly
      run: rustup update nightly && rustup default nightly

    - name: Build
      run: cargo build --verbose

    - name: Test
      run: cargo test --verbose

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: BlobOS.bin
        path: target/x86_64-BlobOS/debug/blob_os
