name: Build & Test BlobOS

on:
  push:
    branches: [ development ]
  pull_request:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  ubuntu:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Rust Nightly
      run: rustup update nightly && rustup default nightly

    - name: Install rust-src
      run: rustup component add rust-src --toolchain nightly

    - name: Install llvm-tools-preview
      run: rustup component add llvm-tools-preview --toolchain nightly

    - name: Install bootimage
      run: cargo install bootimage
    - name: Install QEMU
      run: sudo apt install -y qemu-kvm
      
    - name: Cache rust
      uses: Swatinem/rust-cache@v2

    - name: Build
      run: cargo bootimage

    - name: Test
      run: cargo test --verbose

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: BlobOS.bin
        path: target/x86_64-BlobOS/debug/bootimage-blob_os.bin*
