name: Build BlobOS

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  ubuntu:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y grub-common mtools nasm cmake

    - name: Build
      run: |
        cmake -S . -B build -G Ninja
        cmake --build build/

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: BlobOS_BIN
        path: build/BlobOS.bin # Change this to the path of your OS build artifacts
