name: Build BlobOS

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  ubuntu:
    name: Build BlobOS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y grub-common mtools nasm cmake make

      - name: Build
        run: |
          make

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: BlobOS
          path: build/BlobOS.iso # Change this to the path of your OS build artifacts
